module.exports = {
  loginFields: [
    {
      label: "email address",
      id: "email-input",
      type: "email",
      name: "email",
      placeholder: "Enter your email address",
      required: true,
      icon: "at",
    },
    {
      label: "password",
      id: "password-input",
      type: "password",
      name: "password",
      placeholder: "******",
      required: true,
      icon: "lock",
    },
  ],
  registerFields: [
    {
      label: "name",
      id: "name-input",
      type: "text",
      name: "name",
      placeholder: "Enter your name",
      required: true,
      value: "",
      icon: "user",
    },
    {
      label: "email address",
      id: "email-input",
      type: "email",
      name: "email",
      placeholder: "Enter your email address",
      required: true,
      value: "",
      icon: "at",
    },
    {
      label: "password",
      id: "pass1-input",
      type: "password",
      name: "pass1",
      placeholder: "Enter a new password",
      required: true,
      value: "",
      icon: "lock",
    },
    {
      label: "re-password",
      id: "pass2-input",
      type: "password",
      name: "pass2",
      placeholder: "Confirm your password",
      required: true,
      value: "",
      icon: "lock",
    },
  ],
}
